name: DCTCore
authors: DockCreaTer
main: DCTCore\DCTCore
api: [2.0.0]
version: 0.0.1#TESTING
commands:
  c:
    description: "use /c help for all parameters"
    permission: f.command
permissions:
  nofall.damage:
    default: true
  saver.inventory.switch:
    description: "Allows switching inventory on world change"
    default: true
  f.command:
    default: true
    description: "Allow use of all clans commands"

